import { useState, useEffect } from "react";
import api from "@/lib/api";
import { toast } from "sonner";
import PageHeader from "@/components/PageHeader";
import {
    ChartLineUp, MagnifyingGlass, Newspaper, Calendar,
    Sparkle, ArrowRight, ArrowsClockwise,
} from "@phosphor-icons/react";

const TABS = [
    { id: "market", label: "Market Analysis", icon: ChartLineUp },
    { id: "seo", label: "SEO Toolkit", icon: MagnifyingGlass },
    { id: "pr", label: "PR & Outreach", icon: Newspaper },
    { id: "plan", label: "12-Month Plan", icon: Calendar },
];

export default function GrowthStudio() {
    const [tab, setTab] = useState("market");
    return (
        <div>
            <PageHeader
                eyebrow="// Growth engine"
                title="Growth Studio"
                subtitle="Market intel, SEO, PR and a 12-month roadmap — generated by AI from your business profile."
            />
            <div className="px-8 py-6">
                {/* Tabs */}
                <div className="flex gap-0 zm-card mb-6 overflow-x-auto" data-testid="growth-tabs">
                    {TABS.map((t) => (
                        <button
                            key={t.id}
                            onClick={() => setTab(t.id)}
                            data-testid={`tab-${t.id}`}
                            className={`flex items-center gap-2 px-6 py-4 text-xs uppercase tracking-[0.15em] font-bold whitespace-nowrap border-r border-[#EDE5D4] last:border-r-0 transition-colors ${
                                tab === t.id ? "bg-[#0E0F11] text-white" : "bg-white text-[#71717A] hover:bg-[#FAF7F2] hover:text-[#0E0F11]"
                            }`}
                        >
                            <t.icon size={14} weight="bold" /> {t.label}
                        </button>
                    ))}
                </div>

                {tab === "market" && <MarketTab />}
                {tab === "seo" && <SEOTab />}
                {tab === "pr" && <PRTab />}
                {tab === "plan" && <PlanTab />}
            </div>
        </div>
    );
}

/* ---------- Market Analysis ---------- */
function MarketTab() {
    const [data, setData] = useState(null);
    const [loading, setLoading] = useState(false);

    const generate = async () => {
        setLoading(true);
        const t = toast.loading("AI analysing your market…");
        try {
            const r = await api.post("/market/analyze", {});
            setData(r.data.analysis.data);
            toast.success("Market analysis ready", { id: t });
        } catch (err) { toast.error("Failed", { id: t }); }
        finally { setLoading(false); }
    };

    return (
        <div className="space-y-6" data-testid="market-tab">
            <ActionBar
                title="Generate competitive market analysis"
                desc="SWOT, market size, competitor matrix, positioning recommendations."
                onClick={generate}
                loading={loading}
                cta={data ? "Regenerate" : "Run analysis"}
            />
            {data && (
                <div className="space-y-6">
                    <div className="grid md:grid-cols-2 gap-0 zm-card">
                        <Block title="Market size">{data.market_size}</Block>
                        <Block title="Growth rate" right>{data.growth_rate}</Block>
                    </div>

                    <Section title="Trends to ride">
                        <ul className="grid md:grid-cols-2 gap-2">
                            {(data.trends || []).map((t, i) => (
                                <li key={i} className="flex gap-2 text-sm bg-[#FAF7F2] p-3 border-l-2 border-[#FF562D]">
                                    <span className="text-[#71717A] font-mono text-xs">{String(i + 1).padStart(2, "0")}</span>
                                    {t}
                                </li>
                            ))}
                        </ul>
                    </Section>

                    <Section title="Competitor matrix">
                        <div className="zm-card overflow-x-auto">
                            <table className="w-full text-sm">
                                <thead>
                                    <tr className="border-b border-[#EDE5D4]">
                                        {["Name", "Strengths", "Weaknesses", "Positioning"].map((h) => (
                                            <th key={h} className="text-left px-4 py-3 zm-section-label">{h}</th>
                                        ))}
                                    </tr>
                                </thead>
                                <tbody>
                                    {(data.competitors || []).map((c, i) => (
                                        <tr key={i} className="border-b border-[#EDE5D4] last:border-b-0 align-top">
                                            <td className="px-4 py-3 font-semibold">{c.name}</td>
                                            <td className="px-4 py-3 text-[#71717A]">{c.strengths}</td>
                                            <td className="px-4 py-3 text-[#71717A]">{c.weaknesses}</td>
                                            <td className="px-4 py-3 text-[#71717A]">{c.positioning}</td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    </Section>

                    <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-0 zm-card">
                        {["strengths", "weaknesses", "opportunities", "threats"].map((k, i) => (
                            <div key={k} className={`p-6 ${i < 3 ? "lg:border-r" : ""} ${i % 2 !== 1 ? "md:border-r" : ""} ${i < 2 ? "md:border-b lg:border-b-0" : ""} border-[#EDE5D4]`}>
                                <p className="zm-section-label mb-3">// {k}</p>
                                <ul className="space-y-2 text-sm">
                                    {(data.swot?.[k] || []).map((it, j) => <li key={j} className="text-[#0E0F11]">• {it}</li>)}
                                </ul>
                            </div>
                        ))}
                    </div>

                    <Section title="Positioning recommendation">
                        <p className="text-sm leading-relaxed bg-[#0E0F11] text-white p-6 zm-card border-0">{data.positioning_recommendation}</p>
                    </Section>

                    <Section title="Differentiator angles">
                        <ul className="space-y-2">
                            {(data.unique_angles || []).map((a, i) => (
                                <li key={i} className="text-sm flex gap-3">
                                    <span className="zm-badge bg-[#FF562D] text-white">{String(i + 1).padStart(2, "0")}</span>
                                    {a}
                                </li>
                            ))}
                        </ul>
                    </Section>

                    <Section title="Immediate actions">
                        <div className="zm-card divide-y divide-[#EDE5D4]">
                            {(data.immediate_actions || []).map((a, i) => {
                                const text = typeof a === "string" ? a : (a.action || a.step || "");
                                const priority = typeof a === "object" ? a.priority : null;
                                return (
                                    <div key={i} className="px-6 py-4 flex items-center gap-3">
                                        <span className="text-xs text-[#71717A] font-mono">{String(i + 1).padStart(2, "0")}</span>
                                        <span className="flex-1 text-sm">{text}</span>
                                        {priority && <span className={`zm-badge ${priority === "high" ? "bg-[#E32636] text-white" : priority === "med" ? "bg-[#F59E0B] text-white" : "bg-[#FAF7F2] text-[#0E0F11]"}`}>{priority}</span>}
                                    </div>
                                );
                            })}
                        </div>
                    </Section>
                </div>
            )}
        </div>
    );
}

/* ---------- SEO Toolkit ---------- */
function SEOTab() {
    const [sub, setSub] = useState("keywords");
    return (
        <div>
            <div className="flex gap-2 mb-6">
                {[["keywords", "Keywords"], ["backlinks", "Backlinks"], ["content", "Content gaps"]].map(([id, label]) => (
                    <button
                        key={id}
                        onClick={() => setSub(id)}
                        data-testid={`seo-sub-${id}`}
                        className={`px-4 py-2 text-xs uppercase tracking-[0.15em] font-bold border ${
                            sub === id ? "bg-[#FF562D] border-[#FF562D] text-white" : "bg-white border-[#EDE5D4] text-[#71717A] hover:border-[#FF562D]"
                        }`}
                    >{label}</button>
                ))}
            </div>
            {sub === "keywords" && <KeywordList />}
            {sub === "backlinks" && <BacklinkList />}
            {sub === "content" && <ContentGapList />}
        </div>
    );
}

function KeywordList() {
    const [seed, setSeed] = useState("");
    const [items, setItems] = useState([]);
    const [loading, setLoading] = useState(false);
    const run = async () => {
        setLoading(true);
        const t = toast.loading("Researching keywords…");
        try {
            const r = await api.post("/seo/keywords", { seed_keyword: seed });
            setItems(r.data.keywords || []);
            toast.success(`${(r.data.keywords || []).length} keywords found`, { id: t });
        } catch { toast.error("Failed", { id: t }); }
        finally { setLoading(false); }
    };
    return (
        <div className="space-y-4" data-testid="keyword-tab">
            <div className="flex gap-2">
                <input className="zm-input flex-1" placeholder="Seed keyword (defaults to your industry)" value={seed} onChange={(e) => setSeed(e.target.value)} data-testid="seo-seed" />
                <button onClick={run} disabled={loading} className="zm-btn-primary" data-testid="seo-keywords-run">
                    <Sparkle size={14} weight="fill" /> {loading ? "Researching…" : "Generate"}
                </button>
            </div>
            {items.length > 0 && (
                <div className="zm-card overflow-x-auto">
                    <table className="w-full text-sm">
                        <thead>
                            <tr className="border-b border-[#EDE5D4]">
                                {["Keyword", "Intent", "Difficulty", "Volume", "Opportunity", "Category"].map((h) => (
                                    <th key={h} className="text-left px-4 py-3 zm-section-label">{h}</th>
                                ))}
                            </tr>
                        </thead>
                        <tbody>
                            {items.map((k, i) => (
                                <tr key={i} className="border-b border-[#EDE5D4] last:border-b-0">
                                    <td className="px-4 py-3 font-semibold">{k.keyword}</td>
                                    <td className="px-4 py-3"><span className="zm-badge bg-[#FAF7F2] text-[#0E0F11]">{k.intent}</span></td>
                                    <td className="px-4 py-3 font-mono text-xs">{k.difficulty}</td>
                                    <td className="px-4 py-3 font-mono text-xs">{k.volume_band}</td>
                                    <td className="px-4 py-3">
                                        <ScoreBar value={k.opportunity_score} />
                                    </td>
                                    <td className="px-4 py-3 text-[#71717A] text-xs">{k.category}</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            )}
        </div>
    );
}

function BacklinkList() {
    const [items, setItems] = useState([]);
    const [loading, setLoading] = useState(false);
    const run = async () => {
        setLoading(true);
        const t = toast.loading("Mapping backlinks…");
        try {
            const r = await api.post("/seo/backlinks", {});
            setItems(r.data.opportunities || []);
            toast.success("Backlinks mapped", { id: t });
        } catch { toast.error("Failed", { id: t }); }
        finally { setLoading(false); }
    };
    return (
        <div className="space-y-4" data-testid="backlink-tab">
            <ActionBar title="Map link-building opportunities" desc="Guest posts, listicles, podcasts, niche directories — ranked by effort/priority." onClick={run} loading={loading} cta="Generate opportunities" />
            {items.length > 0 && (
                <div className="grid md:grid-cols-2 gap-4">
                    {items.map((o, i) => (
                        <div key={i} className="zm-card p-5">
                            <div className="flex items-start justify-between mb-2">
                                <div>
                                    <h4 className="font-semibold text-sm">{o.name}</h4>
                                    <p className="text-xs text-[#71717A] truncate">{o.url}</p>
                                </div>
                                <span className={`zm-badge ${o.priority === "high" ? "bg-[#E32636] text-white" : o.priority === "med" ? "bg-[#F59E0B] text-white" : "bg-[#FAF7F2] text-[#0E0F11]"}`}>{o.priority}</span>
                            </div>
                            <div className="flex gap-2 my-3 text-[10px] uppercase tracking-[0.15em] font-bold text-[#71717A]">
                                <span>DA {o.domain_authority}</span><span>·</span>
                                <span>{o.type}</span><span>·</span>
                                <span>{o.effort} effort</span>
                            </div>
                            <p className="text-xs text-[#71717A] leading-relaxed border-l-2 border-[#FF562D] pl-3">{o.angle}</p>
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
}

function ContentGapList() {
    const [items, setItems] = useState([]);
    const [loading, setLoading] = useState(false);
    const run = async () => {
        setLoading(true);
        const t = toast.loading("Finding content gaps…");
        try {
            const r = await api.post("/seo/content-gaps", {});
            setItems(r.data.content_ideas || []);
            toast.success("Content gaps mapped", { id: t });
        } catch { toast.error("Failed", { id: t }); }
        finally { setLoading(false); }
    };
    return (
        <div className="space-y-4" data-testid="content-gap-tab">
            <ActionBar title="Surface high-intent content opportunities" desc="Titles, formats, funnel stage, outline and word count for each." onClick={run} loading={loading} cta="Generate content plan" />
            {items.length > 0 && (
                <div className="grid md:grid-cols-2 gap-4">
                    {items.map((c, i) => (
                        <div key={i} className="zm-card p-5">
                            <div className="flex items-start justify-between gap-2 mb-2">
                                <h4 className="font-display text-base font-bold tracking-tight">{c.title}</h4>
                                <span className="zm-badge bg-[#0E0F11] text-white">{c.funnel_stage}</span>
                            </div>
                            <div className="flex gap-2 mb-3 text-[10px] uppercase tracking-[0.15em] font-bold text-[#71717A]">
                                <span>{c.format}</span><span>·</span><span>{c.word_count_estimate} words</span>
                            </div>
                            <p className="text-xs text-[#71717A] mb-3"><span className="font-bold text-[#0E0F11]">Target keyword:</span> {c.target_keyword}</p>
                            <details className="text-xs">
                                <summary className="cursor-pointer text-[#FF562D] font-bold uppercase tracking-[0.15em]">View outline</summary>
                                <ul className="mt-2 space-y-1 text-[#71717A] list-disc list-inside">
                                    {(c.content_outline || []).map((s, j) => <li key={j}>{s}</li>)}
                                </ul>
                            </details>
                            <p className="text-xs text-[#A1A1AA] mt-3 italic">{c.why_now}</p>
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
}

/* ---------- PR & Outreach ---------- */
function PRTab() {
    const [sub, setSub] = useState("release");
    return (
        <div>
            <div className="flex gap-2 mb-6">
                {[["release", "Press release"], ["media", "Media list"], ["outreach", "Outreach email"]].map(([id, label]) => (
                    <button
                        key={id} onClick={() => setSub(id)}
                        data-testid={`pr-sub-${id}`}
                        className={`px-4 py-2 text-xs uppercase tracking-[0.15em] font-bold border ${
                            sub === id ? "bg-[#FF562D] border-[#FF562D] text-white" : "bg-white border-[#EDE5D4] text-[#71717A] hover:border-[#FF562D]"
                        }`}
                    >{label}</button>
                ))}
            </div>
            {sub === "release" && <PressRelease />}
            {sub === "media" && <MediaList />}
            {sub === "outreach" && <OutreachComposer />}
        </div>
    );
}

function PressRelease() {
    const [announcement, setAnnouncement] = useState("");
    const [out, setOut] = useState(null);
    const [loading, setLoading] = useState(false);
    const run = async () => {
        if (!announcement) { toast.error("What's the news?"); return; }
        setLoading(true);
        const t = toast.loading("Drafting press release…");
        try {
            const r = await api.post("/pr/press-release", { announcement });
            setOut(r.data.press_release);
            toast.success("Press release ready", { id: t });
        } catch { toast.error("Failed", { id: t }); }
        finally { setLoading(false); }
    };
    return (
        <div className="space-y-4" data-testid="press-release-tab">
            <textarea rows={3} className="zm-input" placeholder="What's the announcement? (e.g. 'We just raised our seed round')" value={announcement} onChange={(e) => setAnnouncement(e.target.value)} data-testid="pr-announcement" />
            <button onClick={run} disabled={loading} className="zm-btn-primary" data-testid="pr-generate"><Sparkle size={14} weight="fill" /> {loading ? "Drafting…" : "Draft press release"}</button>
            {out && (
                <div className="zm-card p-8 space-y-4 max-w-3xl">
                    <p className="zm-section-label">{out.dateline}</p>
                    <h2 className="font-display text-3xl font-black tracking-tighter">{out.headline}</h2>
                    {out.subhead && <p className="text-base text-[#71717A] italic">{out.subhead}</p>}
                    <div className="text-sm leading-relaxed whitespace-pre-wrap text-[#0E0F11]">{out.body}</div>
                    {out.quote && <blockquote className="border-l-4 border-[#FF562D] pl-4 italic text-sm text-[#71717A]">"{out.quote}"</blockquote>}
                    <hr className="border-[#EDE5D4]" />
                    <p className="text-xs text-[#71717A] font-bold uppercase tracking-[0.15em]">About</p>
                    <p className="text-xs text-[#71717A]">{out.boilerplate}</p>
                    <p className="text-xs text-[#A1A1AA]">{out.media_contact}</p>
                </div>
            )}
        </div>
    );
}

function MediaList() {
    const [items, setItems] = useState([]);
    const [loading, setLoading] = useState(false);
    const run = async () => {
        setLoading(true);
        const t = toast.loading("Building media list…");
        try {
            const r = await api.post("/pr/media-list", {});
            setItems(r.data.outlets || []);
            toast.success("Media list ready", { id: t });
        } catch { toast.error("Failed", { id: t }); }
        finally { setLoading(false); }
    };
    return (
        <div className="space-y-4" data-testid="media-list-tab">
            <ActionBar title="Targeted journalist & publication list" desc="12 outlets with beat, contact name, email pattern and angle." onClick={run} loading={loading} cta="Build media list" />
            {items.length > 0 && (
                <div className="zm-card overflow-x-auto">
                    <table className="w-full text-sm">
                        <thead>
                            <tr className="border-b border-[#EDE5D4]">
                                {["Publication", "Beat", "Contact", "Email", "Reach", "Angle"].map((h) => <th key={h} className="text-left px-4 py-3 zm-section-label">{h}</th>)}
                            </tr>
                        </thead>
                        <tbody>
                            {items.map((o, i) => (
                                <tr key={i} className="border-b border-[#EDE5D4] last:border-b-0 align-top">
                                    <td className="px-4 py-3 font-semibold">{o.publication}</td>
                                    <td className="px-4 py-3 text-[#71717A] text-xs">{o.beat}</td>
                                    <td className="px-4 py-3">{o.contact_name}</td>
                                    <td className="px-4 py-3 font-mono text-xs text-[#71717A]">{o.email_pattern}</td>
                                    <td className="px-4 py-3"><span className="zm-badge bg-[#FAF7F2] text-[#0E0F11]">{o.reach}</span></td>
                                    <td className="px-4 py-3 text-[#71717A] text-xs max-w-md">{o.angle}</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            )}
        </div>
    );
}

function OutreachComposer() {
    const [form, setForm] = useState({ journalist_name: "", publication: "", angle: "", announcement: "" });
    const [out, setOut] = useState(null);
    const [loading, setLoading] = useState(false);
    const run = async () => {
        setLoading(true);
        try {
            const r = await api.post("/pr/outreach-email", form);
            setOut(r.data.email);
            toast.success("Email drafted");
        } catch { toast.error("Failed"); }
        finally { setLoading(false); }
    };
    return (
        <div className="space-y-4 max-w-2xl" data-testid="outreach-tab">
            <div className="grid grid-cols-2 gap-3">
                {["journalist_name", "publication"].map((k) => (
                    <div key={k}>
                        <label className="zm-label">{k.replace("_", " ")}</label>
                        <input className="zm-input" value={form[k]} onChange={(e) => setForm({ ...form, [k]: e.target.value })} data-testid={`outreach-${k}`} />
                    </div>
                ))}
            </div>
            <div>
                <label className="zm-label">Angle</label>
                <input className="zm-input" value={form.angle} onChange={(e) => setForm({ ...form, angle: e.target.value })} data-testid="outreach-angle" />
            </div>
            <div>
                <label className="zm-label">Announcement</label>
                <textarea rows={2} className="zm-input" value={form.announcement} onChange={(e) => setForm({ ...form, announcement: e.target.value })} data-testid="outreach-announcement" />
            </div>
            <button onClick={run} disabled={loading} className="zm-btn-primary" data-testid="outreach-generate"><Sparkle size={14} weight="fill" /> {loading ? "Drafting…" : "Draft personalised pitch"}</button>
            {out && (
                <div className="zm-card p-6">
                    <p className="zm-section-label mb-1">Subject</p>
                    <p className="font-display text-lg font-bold mb-4">{out.subject}</p>
                    <p className="zm-section-label mb-1">Body</p>
                    <p className="text-sm whitespace-pre-wrap leading-relaxed">{out.body}</p>
                </div>
            )}
        </div>
    );
}

/* ---------- 12-Month Plan ---------- */
function PlanTab() {
    const [data, setData] = useState(null);
    const [loading, setLoading] = useState(false);
    const [savingChannels, setSavingChannels] = useState(false);

    // Load latest plan if exists
    useEffect(() => {
        api.get("/growth-plan/latest").then((r) => {
            if (r.data.plan) setData(r.data.plan.plan);
        }).catch(() => {});
    }, []);

    const generate = async () => {
        setLoading(true);
        const t = toast.loading("Building 12-month plan…");
        try {
            const r = await api.post("/growth-plan/generate");
            setData(r.data.plan.plan);
            toast.success("12-month plan ready", { id: t });
        } catch { toast.error("Failed", { id: t }); }
        finally { setLoading(false); }
    };

    const updateChannel = (idx, patch) => {
        const channels = [...(data.channel_distribution || [])];
        channels[idx] = { ...channels[idx], ...patch };
        setData({ ...data, channel_distribution: channels });
    };

    const removeChannel = (idx) => {
        const channels = data.channel_distribution.filter((_, i) => i !== idx);
        setData({ ...data, channel_distribution: channels });
    };

    const addChannel = () => {
        const channels = [
            ...(data.channel_distribution || []),
            { name: "New channel", type: "organic", monthly_budget_usd: 0, expected_leads_per_month: 0, expected_cpl_usd: 0, priority: "medium", rationale: "" },
        ];
        setData({ ...data, channel_distribution: channels });
    };

    const saveChannels = async () => {
        setSavingChannels(true);
        try {
            await api.post("/growth-plan/channels", {
                channel_distribution: data.channel_distribution,
                monthly_lead_target: data.monthly_lead_target,
                monthly_budget_usd: data.monthly_budget_usd,
                avg_deal_value_usd: data.avg_deal_value_usd,
            });
            toast.success("Plan overrides saved");
        } catch (err) {
            toast.error(err.response?.data?.detail || "Save failed");
        } finally { setSavingChannels(false); }
    };

    const channels = data?.channel_distribution || [];
    const totalBudget = channels.reduce((s, c) => s + (Number(c.monthly_budget_usd) || 0), 0);
    const totalLeads = channels.reduce((s, c) => s + (Number(c.expected_leads_per_month) || 0), 0);
    const paidBudget = channels.filter((c) => c.type === "paid").reduce((s, c) => s + (Number(c.monthly_budget_usd) || 0), 0);
    const organicBudget = totalBudget - paidBudget;

    return (
        <div className="space-y-6" data-testid="plan-tab">
            <ActionBar title="Generate a comprehensive 12-month growth plan" desc="Vision, north-star metric, paid + organic channel mix, monthly milestones, hiring plan." onClick={generate} loading={loading} cta={data ? "Regenerate plan" : "Generate plan"} />
            {data && (
                <div className="space-y-6">
                    <div className="zm-card bg-[#0E0F11] text-white border-0 p-8 rounded-2xl">
                        <p className="text-[10px] uppercase tracking-[0.25em] text-white/60 font-bold mb-2">// Vision</p>
                        <p className="font-display text-2xl font-bold tracking-tight leading-snug">{data.vision}</p>
                        <div className="mt-6 pt-6 border-t border-white/10 grid sm:grid-cols-2 gap-6">
                            <div>
                                <p className="text-[10px] uppercase tracking-[0.25em] text-white/60 font-bold mb-1">North-star metric</p>
                                <p className="font-display text-2xl font-black tracking-tighter text-[#FF562D]">{data.north_star_metric}</p>
                            </div>
                            <div className="grid grid-cols-3 gap-3">
                                <KpiBlock label="Lead target" value={data.monthly_lead_target || "—"} />
                                <KpiBlock label="Monthly budget" value={data.monthly_budget_usd ? `$${data.monthly_budget_usd}` : "—"} />
                                <KpiBlock label="Avg deal" value={data.avg_deal_value_usd ? `$${data.avg_deal_value_usd}` : "—"} />
                            </div>
                        </div>
                    </div>

                    {/* CHANNEL DISTRIBUTION (paid vs organic, editable) */}
                    {channels.length > 0 && (
                        <Section title="Channel distribution (paid + organic)">
                            <div className="zm-card overflow-hidden" data-testid="channel-distribution">
                                <div className="p-5 border-b border-[#EDE5D4] bg-[#FAF7F2] flex flex-wrap items-center justify-between gap-3">
                                    <div className="flex flex-wrap gap-4">
                                        <div>
                                            <p className="zm-section-label">Total budget</p>
                                            <p className="font-display text-xl font-black tracking-tighter">${totalBudget.toLocaleString()}</p>
                                        </div>
                                        <div className="border-l border-[#EDE5D4] pl-4">
                                            <p className="zm-section-label">Paid</p>
                                            <p className="font-display text-xl font-black tracking-tighter text-[#FF562D]">${paidBudget.toLocaleString()}</p>
                                        </div>
                                        <div className="border-l border-[#EDE5D4] pl-4">
                                            <p className="zm-section-label">Organic</p>
                                            <p className="font-display text-xl font-black tracking-tighter text-[#0FB39A]">${organicBudget.toLocaleString()}</p>
                                        </div>
                                        <div className="border-l border-[#EDE5D4] pl-4">
                                            <p className="zm-section-label">Expected leads</p>
                                            <p className="font-display text-xl font-black tracking-tighter">{totalLeads}</p>
                                        </div>
                                    </div>
                                    <div className="flex gap-2">
                                        <button onClick={addChannel} className="zm-btn-secondary text-xs" data-testid="add-channel">
                                            <Sparkle size={12} weight="bold" /> Add channel
                                        </button>
                                        <button onClick={saveChannels} disabled={savingChannels} className="zm-btn-primary text-xs" data-testid="save-channels">
                                            {savingChannels ? "Saving…" : "Save overrides"}
                                        </button>
                                    </div>
                                </div>

                                {/* Stacked paid vs organic bar */}
                                {totalBudget > 0 && (
                                    <div className="px-5 pt-4">
                                        <div className="flex h-3 rounded-full overflow-hidden border border-[#EDE5D4]">
                                            <div className="bg-[#FF562D]" style={{ width: `${(paidBudget / totalBudget) * 100}%` }}></div>
                                            <div className="bg-[#0FB39A]" style={{ width: `${(organicBudget / totalBudget) * 100}%` }}></div>
                                        </div>
                                        <div className="flex justify-between text-[10px] uppercase tracking-[0.12em] font-bold text-[#71717A] mt-1.5">
                                            <span>Paid {totalBudget ? Math.round(paidBudget / totalBudget * 100) : 0}%</span>
                                            <span>Organic {totalBudget ? Math.round(organicBudget / totalBudget * 100) : 0}%</span>
                                        </div>
                                    </div>
                                )}

                                <div className="overflow-x-auto">
                                    <table className="w-full text-sm">
                                        <thead>
                                            <tr className="border-b border-[#EDE5D4] bg-[#FAF7F2]">
                                                <th className="text-left px-5 py-3 zm-section-label">Channel</th>
                                                <th className="text-left px-3 py-3 zm-section-label">Type</th>
                                                <th className="text-right px-3 py-3 zm-section-label">Budget /mo</th>
                                                <th className="text-right px-3 py-3 zm-section-label">Leads /mo</th>
                                                <th className="text-right px-3 py-3 zm-section-label">CPL</th>
                                                <th className="text-left px-3 py-3 zm-section-label">Priority</th>
                                                <th className="text-left px-3 py-3 zm-section-label">Why</th>
                                                <th className="px-3 py-3"></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {channels.map((c, i) => (
                                                <tr key={i} className="border-b border-[#EDE5D4] last:border-b-0 align-top hover:bg-[#FAF7F2]" data-testid={`channel-row-${i}`}>
                                                    <td className="px-5 py-2.5">
                                                        <input className="zm-input text-sm py-1.5 font-semibold" value={c.name || ""} onChange={(e) => updateChannel(i, { name: e.target.value })} data-testid={`channel-name-${i}`} />
                                                    </td>
                                                    <td className="px-3 py-2.5">
                                                        <select className="zm-input text-xs py-1.5" value={c.type || "organic"} onChange={(e) => updateChannel(i, { type: e.target.value })} data-testid={`channel-type-${i}`}>
                                                            <option value="paid">Paid</option>
                                                            <option value="organic">Organic</option>
                                                        </select>
                                                    </td>
                                                    <td className="px-3 py-2.5 w-28">
                                                        <input type="number" min="0" className="zm-input text-sm py-1.5 text-right" value={c.monthly_budget_usd || 0} onChange={(e) => updateChannel(i, { monthly_budget_usd: Number(e.target.value) })} data-testid={`channel-budget-${i}`} />
                                                    </td>
                                                    <td className="px-3 py-2.5 w-24">
                                                        <input type="number" min="0" className="zm-input text-sm py-1.5 text-right" value={c.expected_leads_per_month || 0} onChange={(e) => updateChannel(i, { expected_leads_per_month: Number(e.target.value) })} data-testid={`channel-leads-${i}`} />
                                                    </td>
                                                    <td className="px-3 py-2.5 w-20">
                                                        <input type="number" min="0" className="zm-input text-sm py-1.5 text-right" value={c.expected_cpl_usd || 0} onChange={(e) => updateChannel(i, { expected_cpl_usd: Number(e.target.value) })} />
                                                    </td>
                                                    <td className="px-3 py-2.5 w-28">
                                                        <select className="zm-input text-xs py-1.5" value={c.priority || "medium"} onChange={(e) => updateChannel(i, { priority: e.target.value })}>
                                                            <option value="high">High</option>
                                                            <option value="medium">Medium</option>
                                                            <option value="low">Low</option>
                                                        </select>
                                                    </td>
                                                    <td className="px-3 py-2.5 min-w-[200px] max-w-[300px] text-xs text-[#52525B]">{c.rationale}</td>
                                                    <td className="px-3 py-2.5">
                                                        <button onClick={() => removeChannel(i)} className="text-[#A1A1AA] hover:text-[#FF562D]" data-testid={`channel-remove-${i}`}>
                                                            <ArrowsClockwise size={12} weight="bold" style={{ transform: "rotate(45deg)" }} />×
                                                        </button>
                                                    </td>
                                                </tr>
                                            ))}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </Section>
                    )}

                    <Section title="Quarterly themes">
                        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">
                            {(data.quarterly_themes || []).map((q, i) => (
                                <div key={i} className="zm-card p-5">
                                    <p className="zm-section-label mb-1">{q.quarter}</p>
                                    <h4 className="font-display text-lg font-bold tracking-tight mb-3">{q.theme}</h4>
                                    <p className="text-xs text-[#71717A] mb-3 italic">{q.primary_goal}</p>
                                    <p className="zm-section-label mt-3 mb-1">Targets</p>
                                    <ul className="text-xs space-y-1 mb-3 text-[#0E0F11]">
                                        {(q.key_targets || []).map((t, j) => <li key={j}>• {t}</li>)}
                                    </ul>
                                    <p className="zm-section-label mt-3 mb-1">Initiatives</p>
                                    <ul className="text-xs space-y-1 text-[#0E0F11]">
                                        {(q.top_3_initiatives || []).map((t, j) => <li key={j}>{j + 1}. {t}</li>)}
                                    </ul>
                                    <div className="mt-4 pt-3 border-t border-[#EDE5D4] text-[10px] uppercase tracking-[0.15em] text-[#71717A] font-bold">
                                        Budget: {q.estimated_budget_band}
                                    </div>
                                </div>
                            ))}
                        </div>
                    </Section>

                    <Section title="Monthly milestones">
                        <div className="zm-card divide-y divide-[#EDE5D4]">
                            {(data.monthly_milestones || []).map((m, i) => (
                                <div key={i} className="px-6 py-4 flex items-center gap-4">
                                    <span className="font-display text-2xl font-black tracking-tighter w-8 text-[#FF562D]">{i + 1}</span>
                                    <span className="text-sm">{m}</span>
                                </div>
                            ))}
                        </div>
                    </Section>

                    <div className="grid md:grid-cols-2 gap-6">
                        <Section title="Hiring plan">
                            <div className="zm-card divide-y divide-[#EDE5D4]">
                                {(data.hiring_plan || []).map((h, i) => {
                                    const role = typeof h === "string" ? h : h.role || h.position || "";
                                    const month = typeof h === "object" ? (h.month || h.quarter || "") : "";
                                    return (
                                        <div key={i} className="px-5 py-3 flex items-center justify-between">
                                            <span className="text-sm">{role}</span>
                                            <span className="zm-badge bg-[#FAF7F2] text-[#0E0F11]">{month}</span>
                                        </div>
                                    );
                                })}
                            </div>
                        </Section>

                        <Section title="Marketing mix">
                            <div className="zm-card p-6 space-y-2.5">
                                {Object.entries(data.marketing_mix || {}).map(([ch, pct]) => (
                                    <div key={ch}>
                                        <div className="flex justify-between text-xs mb-1">
                                            <span className="uppercase tracking-[0.12em] font-bold text-[#71717A]">{ch.replace(/_/g, " ")}</span>
                                            <span className="font-mono font-bold">{pct}%</span>
                                        </div>
                                        <div className="h-2 bg-[#FAF7F2] rounded-full overflow-hidden">
                                            <div className="h-full bg-[#FF562D] rounded-full" style={{ width: `${pct}%` }} />
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </Section>
                    </div>

                    <div className="grid md:grid-cols-2 gap-6">
                        <Section title="Key assumptions">
                            <ul className="zm-card p-6 space-y-2 text-sm text-[#52525B]">
                                {(data.key_assumptions || []).map((a, i) => <li key={i}>• {a}</li>)}
                            </ul>
                        </Section>
                        <Section title="Success KPIs (Month 12)">
                            <ul className="zm-card p-6 space-y-2 text-sm">
                                {(data.success_kpis || []).map((k, i) => <li key={i} className="flex gap-2"><ArrowRight size={14} weight="bold" className="text-[#FF562D] mt-0.5 shrink-0" /> <span>{k}</span></li>)}
                            </ul>
                        </Section>
                    </div>
                </div>
            )}
        </div>
    );
}

function KpiBlock({ label, value }) {
    return (
        <div>
            <p className="text-[9px] uppercase tracking-[0.2em] text-white/50 font-bold mb-1">{label}</p>
            <p className="font-display text-base font-black tracking-tighter">{value}</p>
        </div>
    );
}

/* ---------- Shared subcomponents ---------- */
function ActionBar({ title, desc, onClick, loading, cta }) {
    return (
        <div className="zm-card p-6 flex flex-col md:flex-row md:items-center md:justify-between gap-4">
            <div>
                <h3 className="font-display text-xl font-bold tracking-tight">{title}</h3>
                <p className="text-sm text-[#71717A] mt-1">{desc}</p>
            </div>
            <button onClick={onClick} disabled={loading} className="zm-btn-primary whitespace-nowrap" data-testid="action-bar-generate">
                {loading ? <ArrowsClockwise size={14} weight="bold" className="animate-spin" /> : <Sparkle size={14} weight="fill" />}
                {loading ? "Generating…" : cta}
            </button>
        </div>
    );
}

function Section({ title, children }) {
    return (
        <div>
            <h3 className="font-display text-xl font-bold tracking-tight mb-3">{title}</h3>
            {children}
        </div>
    );
}

function Block({ title, children, right }) {
    return (
        <div className={`p-6 ${right ? "" : "border-r border-[#EDE5D4]"}`}>
            <p className="zm-section-label mb-2">{title}</p>
            <p className="text-sm leading-relaxed">{children}</p>
        </div>
    );
}

function ScoreBar({ value }) {
    const v = Math.max(0, Math.min(100, value || 0));
    const color = v >= 70 ? "#10B981" : v >= 40 ? "#F59E0B" : "#71717A";
    return (
        <div className="flex items-center gap-2">
            <span className="font-mono text-xs font-bold" style={{ color }}>{v}</span>
            <div className="w-12 h-1 bg-[#FAF7F2]"><div className="h-full" style={{ width: `${v}%`, background: color }} /></div>
        </div>
    );
}
